stages:
    - test
    - image

variables:
    REGISTRY_HOST: registry.gitlab.com
    # Dočasné meno image-u. Treba updatnúť na reálne keď sa založí repo na Gitlabe
    TROJSTENWEB_IMAGE_NAME: ${REGISTRY_HOST}/trojsten/trojstenweb

lint:
    stage: test
    image: python:3.6
    before_script:
        - pip install flake8
    script:
        - flake8 trojsten


.test: &test_template
    stage: test
    image: python:3.6
    services:
        - postgres:9.2
        - elasticsearch:2.4.6  # Deprecated image kôli starej verzii. Keď sa
                               # upgradne, použiť podľa návodu:
                               # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
    variables:
        POSTGRES_DB: trojsten
        POSTGRES_USER: trojsten
        POSTGRES_PASSWORD: ""
        TROJSTENWEB_DATABASE_URL: postgres
        TROJSTENWEB_HAYSTACK_CONNECTIONS_URL: http://elasticsearch:9200
        DJANGO_SETTINGS_MODULE: trojsten.settings.test
    before_script:
        - apt-get update -qy && apt-get install -y gettext librsvg
        - |
          case "${PYTHON_VERSION}" in
            3*)
                pip install -r requirements3.txt
                ;;
            *)
                pip install -r requirements.txt
                ;;
          esac
        - pip install -q coverage
        - bash -c 'cd trojsten; python ../manage.py compilemessages;'
    script:
        - coverage run --source='./trojsten' --omit 'trojsten/settings/*,trojsten/special/*' manage.py test

test-py3:
    <<: *test_template
    image: python:3.6

test-py2:
    <<: *test_template
    image: python:2.7


.tagged_image: &tagged_image_template
    image: docker:stable
    services:
        - docker:dind
    stage: image
    script:
        - docker build . --no-cache --pull -t "${TROJSTENWEB_IMAGE_NAME}:${TROJSTENWEB_IMAGE_TAG}"
        - docker login -u gitlab-ci-token -p "${CI_BUILD_TOKEN}" "${REGISTRY_HOST}"
        - docker push "${TROJSTENWEB_IMAGE_NAME}:${TROJSTENWEB_IMAGE_TAG}"
    variables:
        TROJSTENWEB_IMAGE_TAG: latest

latest-image:
    <<: *tagged_image_template
    variables:
        TROJSTENWEB_IMAGE_TAG: "latest"
    only:
      - master

tagged-image:
    <<: *tagged_image_template
    variables:
        TROJSTENWEB_IMAGE_TAG: ${CI_COMMIT_REF_NAME}
    only:
      - tags

testing-image:
    image: docker:stable
    services:
        - docker:dind
    stage: image
    script:
        - docker build . --no-cache --pull -t ${TROJSTENWEB_IMAGE_NAME}
    except:
        - master
        - tags
